In [2]:
import torch

In [11]:
# Создайте случайный FloatTensor размера 3x4x5
ftsr=torch.randn(3,4,5).type(torch.FloatTensor)
ftsr

tensor([[[-1.5490, -0.5485,  0.5160, -1.6021,  1.2680],
         [ 0.9814,  0.6676, -0.3310,  0.9185,  0.5870],
         [-0.8282, -0.9471,  0.0027, -0.2593,  0.6044],
         [-0.0787,  0.1981, -0.4082,  0.2270, -0.3960]],

        [[-0.1196, -1.0349, -0.2805, -1.1502,  1.1282],
         [-0.4705,  1.4417,  1.4214, -0.4969, -1.4428],
         [ 0.6022, -0.5223, -0.4652,  0.3791,  1.9318],
         [ 1.0282, -1.3391,  0.8451,  0.4797,  1.5098]],

        [[-0.5076,  0.1868,  1.0273,  1.5171,  1.1197],
         [ 0.7691,  1.0461, -0.2144,  0.4391,  0.6311],
         [-0.8709, -1.5103,  0.1928, -0.2026,  0.9447],
         [-0.5487,  0.3098,  1.2746, -0.3954,  0.4050]]])

In [12]:
# Выведите его форму (shape)
ftsr.shape

torch.Size([3, 4, 5])

In [13]:
# Приведите его к форме 6 X 10
ftsr.resize_(6,10)
ftsr.shape

torch.Size([6, 10])

In [42]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
ftsr=ftsr*torch.FloatTensor([1, 4, 2, 2, 1,5,2,8,1,0])
ftsr

tensor([[-1.5490e+00, -2.1941e+00,  1.0321e+00, -3.2042e+00,  1.2680e+00,
          4.9071e+00,  1.3352e+00, -2.6481e+00,  9.1854e-01,  0.0000e+00],
        [-8.2821e-01, -3.7884e+00,  5.3783e-03, -5.1859e-01,  6.0436e-01,
         -3.9360e-01,  3.9623e-01, -3.2656e+00,  2.2701e-01, -0.0000e+00],
        [-1.1957e-01, -4.1396e+00, -5.6106e-01, -2.3005e+00,  1.1282e+00,
         -2.3524e+00,  2.8835e+00,  1.1371e+01, -4.9694e-01, -0.0000e+00],
        [ 6.0222e-01, -2.0891e+00, -9.3034e-01,  7.5829e-01,  1.9318e+00,
          5.1409e+00, -2.6782e+00,  6.7610e+00,  4.7973e-01,  0.0000e+00],
        [-5.0765e-01,  7.4711e-01,  2.0546e+00,  3.0342e+00,  1.1197e+00,
          3.8454e+00,  2.0922e+00, -1.7155e+00,  4.3909e-01,  0.0000e+00],
        [-8.7087e-01, -6.0414e+00,  3.8554e-01, -4.0527e-01,  9.4467e-01,
         -2.7434e+00,  6.1966e-01,  1.0197e+01, -3.9535e-01,  0.0000e+00]])

In [33]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
ftsr_2=torch.matmul(ftsr,torch.transpose(ftsr,0,1))
ftsr_2.shape

torch.Size([6, 6])

In [38]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x=torch.tensor(1.0,requires_grad=True)
z=torch.tensor(0.5,requires_grad=True)
t=torch.tensor(2.0,requires_grad=True)
y=x**3+z-75*t
y.backward()
print(x.grad)
print("*"*20)
print(z.grad)
print("*"*20)
print(t.grad)
print("*"*20)

tensor(3.)
********************
tensor(1.)
********************
tensor(-75.)
********************


In [39]:
# Создайте единичный тензор размера 5x6
ones=torch.ones(5,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [41]:
# Переведите его в формат numpy
ones=ones.numpy()
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)